[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mydisease-mcp"
version = "0.1.0"
description = "MCP server providing comprehensive access to MyDisease.info API for disease information"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    {name = "Zhong Ren", email = "zhong.ren@hotmail.com"},
]
keywords = [
    "mcp",
    "mydisease",
    "disease",
    "api",
    "omim",
    "orphanet",
    "disgenet",
    "clinvar",
    "gwas",
    "bioinformatics",
    "medical-informatics"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
dependencies = [
    "mcp>=1.0.0",
    "httpx>=0.27.0",
    "pydantic>=2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.12.0",
    "black>=24.0.0",
    "ruff>=0.4.0",
    "mypy>=1.10.0",
]

[project.scripts]
mydisease-mcp = "mydisease_mcp.server:main"

[project.urls]
Homepage = "https://github.com/nickzren/mydisease-mcp"
Documentation = "https://github.com/nickzren/mydisease-mcp#readme"
Repository = "https://github.com/nickzren/mydisease-mcp"
Issues = "https://github.com/nickzren/mydisease-mcp/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/mydisease_mcp"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = "-v --cov=mydisease_mcp --cov-report=term-missing --cov-report=html"

[tool.coverage.run]
source = ["src/mydisease_mcp"]
omit = ["*/tests/*", "*/__init__.py"]

[tool.ruff]
line-length = 100
target-version = "py311"