name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: mydisease-mcp
          cache-environment: true
          init-shell: bash

      - name: Run tests
        shell: bash -l {0}
        run: |
          echo "Running tests in environment: $CONDA_DEFAULT_ENV"
          micromamba info
          micromamba list
          pytest tests/ -v